'use client'
import { useState } from 'react'
import Link from 'next/link'
import { Bell, Heart, MapPin, Menu, MessageCircle, Search, X } from 'lucide-react'
import { nav, pets } from '@/lib/pet-data'
export function SiteShell({children}:{children:React.ReactNode}) { const [open,setOpen]=useState(false); return <main className="app-shell"><header className="topbar"><Link className="brand" href="/"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/name-kPFgxcBG1toR0Q3Vjuixc2AF6NWEst.png" alt="PetMorChor"/></Link><div className="header-search"><Search size={18}/><input aria-label="ค้นหาสัตว์เลี้ยง โพสต์ หรือข้อมูล" placeholder="ค้นหาสัตว์เลี้ยง โพสต์ หรือข้อมูล..."/></div><div className="header-actions"><Link href="/chat"><MessageCircle size={19}/>แชต</Link><Link href="/notifications"><Bell size={19}/>การแจ้งเตือน</Link><Link href="/profile"><span className="avatar">P</span>โปรไฟล์</Link></div><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header><nav className={`main-nav ${open?'open':''}`}>{nav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link className="post-listing" href="/create">+ Post Something</Link></nav><div className="location-bar"><MapPin size={17}/><div><b>พื้นที่ของคุณ</b><span>มหาวิทยาลัยและพื้นที่ใกล้เคียง</span></div><button>เปลี่ยนสถานที่</button></div>{children}<footer><Link className="brand" href="/"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/name-kPFgxcBG1toR0Q3Vjuixc2AF6NWEst.png" alt="PetMorChor"/></Link><p>พื้นที่สำหรับสัตว์เลี้ยงและคนรักสัตว์รอบมหาวิทยาลัย</p><small>© 2026 PetMorChor · มหาวิทยาลัยและพื้นที่ใกล้เคียง</small></footer><div className="bottom-nav"><Link href="/">หน้าแรก</Link><Link href="/discover">ค้นหาใกล้ฉัน</Link><Link href="/create" className="plus">+</Link><Link href="/chat">แชต</Link><Link href="/profile">โปรไฟล์</Link></div></main> }
export function Eyebrow({children}:{children:React.ReactNode}){return <span className="eyebrow">{children}</span>}
export function PageFrame({title,subtitle,children,eyebrow='AROUND CAMPUS'}:{title:string;subtitle?:string;children:React.ReactNode;eyebrow?:string}){return <SiteShell><section className="page-frame"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{subtitle&&<p className="lead">{subtitle}</p>}{children}</section></SiteShell>}
export function PetCard({pet}:{pet:any}){return <Link className="pet-card" href={`/marketplace/${pet.id}`}><div className="pet-image"><img src={pet.image} alt={`${pet.name}, ${pet.breed}`}/><span className={`pet-badge ${pet.status==='ADOPTION'?'adoption':'sale'}`}>{pet.status==='ADOPTION'?'หาบ้าน':'ประกาศขาย'}</span><button onClick={e=>e.preventDefault()} aria-label={`บันทึก ${pet.name}`}><Heart size={17}/></button></div><div className="pet-info"><h3>{pet.name}</h3><p>{pet.breed} · {pet.age}</p><p className="pet-meta"><MapPin size={13}/> {pet.place}</p><strong>{pet.distance}</strong></div></Link>}
export function SectionTitle({title,subtitle,href}:{title:string;subtitle?:string;href?:string}){return <div className="section-heading"><div><Eyebrow>ชุมชนใกล้ฉัน</Eyebrow><h2>{title}</h2>{subtitle&&<p className="section-subtitle">{subtitle}</p>}</div>{href&&<Link href={href}>ดูทั้งหมด →</Link>}</div>}
export function ServiceCards(){return <div className="service-grid">{[['Paws & Claws Clinic','Veterinary clinic','0.7 km','4.9'],['Campus Pet Supply','Pet shop','1.1 km','4.7'],['Fluffy Wash','Grooming','1.8 km','4.8']].map(s=><article className="service-card" key={s[0]}><span className="service-icon"><MapPin/></span><h3>{s[0]}</h3><p>{s[1]} · {s[2]}</p><strong>★ {s[3]}</strong></article>)}</div>}
export function PostCards(){return <div className="post-grid">{[{id:'orange-cat',author:'Nina P.',body:'มีใครเจอแมวสีส้มแถวหอ 3 ไหมครับ น้องใส่ปลอกคอสีน้ำเงิน',time:'2h',likes:24,comments:8},{id:'bath-shop',author:'Beam K.',body:'มีร้านอาบน้ำสัตว์ใกล้มหาลัยแนะนำไหมครับ',time:'5h',likes:16,comments:12},{id:'cafeteria-cat',author:'Mew S.',body:'แมวที่โรงอาหารวันนี้ นั่งเฝ้าร้านข้าวเหมือนเป็นเจ้าของเลย',time:'1d',likes:41,comments:6}].map(p=><Link className="post-card" href={`/community/${p.id}`} key={p.id}><div className="post-user"><span className="post-avatar">{p.author[0]}</span><b>{p.author}</b><span>· {p.time}</span></div><p>{p.body}</p><div className="post-actions"><span>♡ {p.likes}</span><span>○ {p.comments} comments</span><span>↗ Share</span></div></Link>)}</div>}
export function ArticleCards(){return <div className="article-grid">{[{id:'dorm-cat',title:'How to care for a cat in a dorm',tag:'CARE',time:'6 min read',image:'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=85'},{id:'adopt-dog',title:'Things to prepare before adopting a dog',tag:'ADOPTION',time:'8 min read',image:'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85'},{id:'stray',title:'What to do when you find a stray around campus',tag:'SAFETY',time:'5 min read',image:'https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=900&q=85'}].map(a=><Link className="article-card" href={`/information/${a.id}`} key={a.id}><img src={a.image} alt=""/><Eyebrow>{a.tag} · {a.time}</Eyebrow><h3>{a.title}</h3></Link>)}</div>}
export function PetGrid(){return <div className="pet-grid">{pets.map(p=><PetCard key={p.id} pet={p}/>)}</div>}
export function Auth({register=false}:{register?:boolean}){return <main className="auth-page"><div className="auth-card"><Link className="brand" href="/"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/name-kPFgxcBG1toR0Q3Vjuixc2AF6NWEst.png" alt="PetMorChor"/></Link><h1>{register?'Join the local pet community':'Welcome back'}</h1><p>{register?'Meet people and pets around campus.':'Sign in to your campus community.'}</p>{register&&<label>Name<input placeholder="Your name"/></label>}<label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label>{register&&<label>Confirm password<input type="password" placeholder="••••••••"/></label>}{!register&&<label className="check"><input type="checkbox"/> Remember me</label>}<button className="primary-cta">{register?'Create account':'Log in'}</button><span>{register?'Already a member? ':'New here? '}<Link href={register?'/login':'/register'}>{register?'Log in':'Register'}</Link></span></div></main>}
export function FormCard({children}:{children:React.ReactNode}){return <div className="form-card">{children}</div>}
export function ChatPanel(){return <div className="chat-layout"><aside><h2>ข้อความ</h2>{['Nina P.','Beam K.','Mew S.'].map((n,i)=><div className="conversation" key={n}><span className="avatar">{n[0]}</span><div><b>{n}</b><p>{i?'That clinic is very kind.':'Mochi is still available.'}</p></div><small>{i?'Yesterday':'10:42'}</small></div>)}</aside><section className="chat-window"><div className="chat-header"><span className="avatar">N</span><div><b>Nina P.</b><small>Near West Campus</small></div></div><div className="messages"><div className="bubble them">Hi! Is Mochi still available?</div><div className="bubble me">Hi Nina, yes! I&apos;m near the west entrance of the university.</div><div className="bubble them">Mochi is still available.</div></div><div className="message-input"><input placeholder="พิมพ์ข้อความ..."/><button>ส่ง</button></div></section></div>}
export function ListingForm(){return <FormCard><label>Animal name<input placeholder="e.g. Mochi"/></label><label>Animal type<select><option>Cat</option><option>Dog</option><option>Small animal</option></select></label><label>Breed<input placeholder="Breed"/></label><label>Age<input placeholder="Age"/></label><label>Description<textarea placeholder="Tell the local community about this animal..."/></label><label>Location<input placeholder="University Dorm Zone"/></label><div className="form-actions"><button className="secondary-cta">Save draft</button><button className="primary-cta">Publish listing</button></div></FormCard>}
export function NotificationList(){return <div className="notification-list">{[['♥','Nina P. liked your pet listing','Mochi · 12 min ago'],['○','Beam K. commented on your post','Local recommendations · 1h ago'],['◌','You have a new message from Mew S.','Chat · 3h ago'],['✓','Your listing reached 42 nearby people','Mochi · Yesterday']].map(n=><article key={n[1]}><span className="notification-icon">{n[0]}</span><div><b>{n[1]}</b><p>{n[2]}</p></div></article>)}</div>}
export function ProfileCard({user='Pim P.'}:{user?:string}){return <div className="profile-card"><span className="profile-avatar">{user[0]}</span><h2>{user}</h2><p>Pet lover around University Campus · Campus community member</p><span className="location-pill"><MapPin size={13}/> Nearby · Member since 2026</span><div className="profile-tabs"><span>Posts</span><span>Pets</span><span>Listings</span><span>Saved</span></div></div>}
export function Hero(){return <section className="hero-market"><div className="hero-banner"><div><Eyebrow>YOUR LOCAL PET COMMUNITY</Eyebrow><h1>คนรักสัตว์<br/><span>ใกล้ตัวคุณ</span></h1><p>เจอน้องที่ถูกใจใกล้ ๆ คุณ พร้อมพูดคุยกับคนรักสัตว์รอบมหาวิทยาลัย</p><div className="hero-actions"><Link className="primary-cta" href="/discover">เริ่มค้นหาเลย →</Link><Link className="secondary-cta" href="/create">ลงประกาศ</Link></div></div><img src="https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=85" alt="Happy dogs playing near campus"/></div></section>}
export function SearchFilters(){return <div className="filter-row"><button className="filter active">All pets</button><button className="filter">Adoption</button><button className="filter">For sale</button><button className="filter">Within 1 km</button><button className="filter">Nearby Dormitories</button></div>}
export function MarketplaceCards(){return <div className="product-grid">{[['Cat Food 1.5kg','฿250','1.4 km away'],['Cloud Nap Bed','฿690','2.1 km away'],['Walkies Set','฿450','0.9 km away']].map(p=><article className="product-card" key={p[0]}><div className="product-copy"><Eyebrow>NEARBY</Eyebrow><h3>{p[0]}</h3><p>Pet essentials · Local seller</p><strong>{p[1]}</strong><span className="distance">{p[2]}</span></div></article>)}</div>}
export function CommunityDetail({id}:{id:string}){return <article className="detail-card"><div className="post-user"><span className="post-avatar">N</span><b>Pet people near campus</b><span>· 2h</span></div><h2>{id.replaceAll('-',' ')}</h2><p>มีใครเจอแมวสีส้มแถวหอ 3 ไหมครับ น้องใส่ปลอกคอสีน้ำเงิน</p><div className="post-actions"><span>♡ 24</span><span>○ 8 comments</span><span>↗ Share</span></div><textarea placeholder="เขียนความคิดเห็น..."/></article>}
export function InfoDetail({id}:{id:string}){return <article className="article-detail"><Eyebrow>CARE GUIDE · 6 MIN READ</Eyebrow><h1>{id.replaceAll('-',' ')}</h1><p className="lead">Simple, local advice for students and neighbors who want pets to thrive.</p><div className="article-body"><p>Living with an animal near campus can be joyful and manageable with a little planning. Start by making a calm, safe space and keeping everyday routines consistent.</p><h2>Start with the basics</h2><p>Keep food, water, enrichment, and health records easy to find. Ask nearby pet owners and local clinics when you need help — the community is here for you.</p></div></article>}
export function AnimalDetail({pet}:{pet:any}){return <div className="animal-detail"><img className="detail-image" src={pet.image} alt={`${pet.name}, ${pet.breed}`}/><div><Eyebrow>{pet.status} · NEARBY</Eyebrow><h1>{pet.name}</h1><p className="lead">{pet.breed} · {pet.age}</p><p className="location-pill"><MapPin size={14}/> {pet.place} · {pet.distance}</p><p>Mochi is a gentle companion who loves sunny windows and quiet afternoons. Looking for a caring home close to campus.</p><div className="hero-actions"><Link className="primary-cta" href="/chat">Chat with owner</Link><button className="secondary-cta">♡ Save</button></div><div className="trust-box">✓ Campus community member<br/>Nearby · Member since 2026</div></div></div>}
export {Link}
